export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';

export const ADMIN_ADD_TEACHER = 'ADMIN_ADD_TEACHER';
export const ADMIN_ADD_STUDENT = 'ADMIN_ADD_STUDENT'
export const ADMIN_DELETE_TEACHER = 'ADMIN_DELETE_TEACHER'
export const ADMIN_DELETE_STUDENT = 'ADMIN_DELETE_STUDENT'
export const ADMIN_FETCH_TEACHERS = 'ADMIN_FETCH_TEACHERS'
export const ADMIN_FETCH_STUDENTS = 'ADMIN_FETCH_STUDENTS'

export const TEACHER_FETCH_STUDENTS = 'TEACHER_FETCH_STUDENTS'
export const TEACHER_ADD_STUDENT = 'TEACHER_ADD_STUDENT'
export const TEACHER_DELETE_STUDENT = 'TEACHER_DELETE_STUDENT'

