export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';

export const AUTH_SIGN_IN_ERROR = 'AUTH_SIGN_IN_ERROR';

export const ADMIN_ADD_TEACHER = 'ADMIN_ADD_TEACHER';
export const ADMIN_ADD_STUDENT = 'ADMIN_ADD_STUDENT'
export const ADMIN_DELETE_TEACHER = 'ADMIN_DELETE_TEACHER'
export const ADMIN_DELETE_STUDENT = 'ADMIN_DELETE_STUDENT'
export const ADMIN_FETCH_TEACHERS = 'ADMIN_FETCH_TEACHERS'
export const ADMIN_FETCH_STUDENTS = 'ADMIN_FETCH_STUDENTS'

export const ADMIN_ADD_USER_ERROR = 'ADMIN_ADD_USER_ERROR';
export const ADMIN_ADD_STUDENT_ERROR = 'ADMIN_ADD_STUDENT_ERROR'
export const ADMIN_DELETE_TEACHER_ERROR = 'ADMIN_DELETE_TEACHER_ERROR'
export const ADMIN_DELETE_STUDENT_ERROR = 'ADMIN_DELETE_STUDENT_ERROR'
export const ADMIN_FETCH_TEACHERS_ERROR = 'ADMIN_FETCH_TEACHERS_ERROR'
export const ADMIN_FETCH_STUDENTS_ERROR = 'ADMIN_FETCH_STUDENTS_ERROR'

export const TEACHER_FETCH_CLASSES = 'TEACHER_FETCH_CLASSES'
export const TEACHER_ADD_CLASS = 'TEACHER_ADD_CLASS'
export const TEACHER_DELETE_CLASS = 'TEACHER_DELETE_CLASS'

